### ISSUE TITLE
Cleanup bigtable::Filters integration test when the underlying emulator bugs are fixed.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#151]
There are a few small bugs in the Cloud Bigtable emulator that we are working around.  The bugs are:

- [ ] GoogleCloudPlatform/google-cloud-go#839
- [ ] GoogleCloudPlatform/google-cloud-go#840
- [ ] GoogleCloudPlatform/google-cloud-go#841
- [ ] GoogleCloudPlatform/google-cloud-go#842
- [ ] GoogleCloudPlatform/google-cloud-go#843

As those bugs clear we should remove the workarounds from the code.

**Comment by jadekler** [comment]
Heads up - https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1135 was recently fixed. (for your checklist)

**Comment by coryan** [comment]
@dbolduc will investigate.

**Comment by dbolduc** [comment]
Current state:

1. We still run IAM integration tests against production. Blocked on cbt emulator capability.
2. We run our instance admin integration tests against our own standalone instance admin emulator. The work to add instance capabilities to the official cbt emulator has been deprioritized. We will probably have to live with this for the time being.
