### ISSUE TITLE
Implement new snapshot and replication APIs in the Cloud Bigtable C++ client

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#329]
This is a rough breakdown of the tasks necessary to implement the new snapshot, replication, and IAM features in the Cloud Bigtable C++ client.  In all cases the "Implement Foo" should be interpreted as "Implement any new wrappers needed for Foo, Implement the unit tests for Foo".

Needed for Beta:

- [x] Update the googleapis to a version that includes these features (#218)
- [x] Update the `Table::Table` constructors to receive an optional `app_profile_id`. (#373)
- [x] Update the existing `Table::` member functions to use the `app_profile_id`. (#374)
- [x] Update the tests to verify the `app_profile_id` is passed on to the RPC calls if set. (#384)
- [x] Implement `TableAdmin::GenerateConsistencyToken`
- [x] Implement `TableAdmin::CheckConsistency`
- [x] Create a sample snippet that uses the `app_profile_id`.
- [ ] Create an integration test for `app_profile_id`.
- [x] Wrap the `CheckConsistency` loop in the client library (#426).

Not for Beta:
- [x] Implement `TableAdmin::CreateTableFromSnapshot`, return a `std::future<>`.
- [ ] Implement `TableAdmin::CreateTableFromSnapshot`, return `void` and take a functor as argument.
- [ ] Implement `TableAdmin::SnapshotTable`, return a `std::future<>`.
- [ ] Implement `TableAdmin::SnapshotTable`, return `void` and take a functor as argument.
- [x] Implement `TableAdmin::GetSnapshot`.
- [x] Implement `TableAdmin::ListSnapshots`.
- [x] Implement `TableAdmin::DeleteSnapshot`.
- [x] Create a sample snippet for `TableAdmin::CreateTableFromSnapshot`.
- [x] Create a sample snippet for `TableAdmin::SnapshotTable` returning `std::future<>`.
- [ ] Create a sample snippet for `TableAdmin::SnapshotTable` using a functor.
- [x] Create a sample snippet for `TableAdmin::GetSnapshot`.
- [x] Create a sample snippet for `TableAdmin::ListSnapshots`.
- [x] Create a sample snippet for `TableAdmin::DeleteSnapshot`.
- [ ] Create an integration test for `TableAdmin::CreateTableFromSnapshot`.
- [ ] Create an integration test for `TableAdmin::SnapshotTable` returning `std::future<>`.
- [ ] Create an integration test for `TableAdmin::SnapshotTable` using a functor.
- [x] Create an integration test for `TableAdmin::GetSnapshot`.
- [x] Create an integration test for `TableAdmin::ListSnapshots`.
- [x] Create an integration test for `TableAdmin::DeleteSnapshot`.
- [x] Create bugs for each one of the items in this list.

**Comment by coryan** [comment]
For the record, @paprat created a breakdown for all the tasks to "implement X".  I have created additional tasks for the integration tests and for sample snippets.

**Comment by mbrukman** [comment]
@coryan, @paprat: are there other issues created for the following beta-blocker items from the list above?

> - Create a sample snippet that uses the `app_profile_id`.
> - Create an integration test for `app_profile_id`.

I can't find them, but maybe I'm not searching correctly.

**Comment by coryan** [comment]
@mbrukman  I do not think you are "searching incorrectly", we never wrote them, just sent a PR (#850) with an example.  Unfortunately I do not know how to write a (meaningful) integration test.  The golang-based emulator ignores the application profile, so we can pass garbage, or nothing, and it would work.  I guess we could extend the C++-based emulator to emulate the table admin and data admin APIs, but that is a lot of work for just one API (and not necessarily a great idea). And using both in the same test is impossible (and they ignore each other, so it does not help anyway).

**Comment by coryan** [comment]
I am going to break this down into smaller bugs and then close it.

- #1052: integration tests for snapshot CRUD operations.
- #1053: integration test for CreateTableFromSnapshot.
- #1054: integration tests for CreateConsistencyToken and friends.
- #1055: sample for GetSnapshot.
-  #1056: Implement sample snippet for TableAdmin::DeleteSnapshot
- #1057: Implement sample snippet for TableAdmin::CreateTableFromSnapshot
- #1058: Implement sample snippet for TableAdmin::ListSnapshots
- #1059: Implement sample snippet for TableAdmin::GenerateConsistencyToken
- #1060: Implement sample snippet for TableAdmin::CheckConsistency
- #1061: Implement sample snippet for TableAdmin::WaitForConsistencyCheck

- #379: Implement Table::SnapshotTable.

I am not going to create bugs for the async / functor functions. Better to delay that until we start that project.
