### ISSUE TITLE
Complete the implementation of InstanceAdmin

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#416]
The current implementation is the bare minimum for the current clients.  Below is the list of tasks to complete the implementation, separated in groups of similar priorities.  Before working on these tasks please create specific issues for each subtask and reference them here:

Required for Beta:
- [x] Implement `InstanceAdmin::CreateInstance` (#418)
- [x] Implement `InstanceAdmin::GetInstance` (#419)
- [x] Implement `InstanceAdmin::DeleteInstance` (#420)
- [x] Implement `InstanceAdmin::PartialUpdateInstance` (#421)
- [x] Implement `InstanceAdmin::CreateCluster` (#422)
- [x] Implement `InstanceAdmin::ListClusters` (#423)
- [x] Implement `InstanceAdmin::GetCluster` (#643)
- [x] Implement `InstanceAdmin::UpdateCluster`  (#424)
- [x] Implement `InstanceAdmin::DeleteCluster` (#425)

Desired for Beta:
- [x] Implement `InstanceAdmin::CreateAppProfile`
- [x] Implement `InstanceAdmin::GetAppProfile`
- [x] Implement `InstanceAdmin::ListAppProfile`
- [x] Implement `InstanceAdmin::UpdateAppProfile` (returns `std::future<>`)
- [x] Implement `InstanceAdmin::DeleteAppProfile`
- [x] Implement `InstanceAdmin::GetIamPolicy`
- [x] Implement `InstanceAdmin::SetIamPolicy`
- [x] Implement `InstanceAdmin::TestIamPermissions`

Do not wrap this operation:
- [x] Implement `InstanceAdmin::UpdateInstance`

Where is says "Implement" above, that means:
- writing the implementation
- the unit tests for "no errors"
- the unit tests for "unrecoverable error"
- the unit test for "recoverable error, check that we retry" (if applicable)
- the unit test for "too many recoverable errors, check that we fail" (if applicable)
- the integration tests,
- and the sample snippet.

**Comment by coryan** [comment]
All done after #939.
