### ISSUE TITLE
Refactor client library code to ::google::cloud

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#496]
We have an internal discussion (in go/gcs-cpp:surface-dd) around the namespace (and headers) for the CBT-C++ classes and headers.  My proposal is to move them to `::google::cloud::bigtable`. Other proposals, such as `::gcp::bigtable` and `::google::bigtable` also have merits, but we will keep the discussion here simple.

If we want to make this change we have to make it now, before Beta.  This change will impact how the library is perceived by external users (part of a larger collection of Google Cloud libraries, or a standalone C++ client for bigtable).

This proposal is to change the namespaces and headers as follows:

|                                  | Before | After |
| --------------------------  | -------------------------------- | -------------------------------- |
| **Include Headers** | `"bigtable/client/table.h"` | `"google/cloud/bigtable/table.h"` |
| **Namespace**        | `::bigtable::Table`            | `::google::cloud::bigtable::Table` | 

FYI: @sduskis @garye @DanielMahu @paprat @hemant-qlogic @manish-qlogic @roopak-qlogic in case they have an opinion they want to express.

FYI: @ghaisa @mbrukman in case this is a terrible idea from a product perspective.

I have broken this down into smaller tasks:

### Cloud Bigtable

- [x] #628 - Move bigtable::* classes to google::cloud::bigtable::*
- [x] #624 - Move bigtable/doc/* to google/cloud/bigtable/doc/*
- [x] #623 - Move bigtable/tools/* to google/cloud/bigtable/tools/*
- [x] #622 - Move bigtable/examples/* to google/cloud/bigtable/examples/*
- [x] #621 - Move bigtable/benchmarks/* to google/cloud/bigtable/benchmarks/*
- [x] #620 - Move bigtable/tests/* to google/cloud/bigtable/tests/*
- [x] #619 - Move bigtable/client/* to google/cloud/bigtable/*

### Cloud Storage

- [x] #618 - Move storage/tests to google/cloud/storage/tests
- [ ] #629 - Move storage::* classes to google::cloud::storage::*
- [x] #617 - Move storage/client to google/cloud/storage/ storage

### Cloud Firestore

- [x] #630 - Move firestore::* classes to google::cloud::firestore::*

**Comment by hemant-qlogic** [comment]
I think can we have a hierarchy like this.
All the classes which are directly related to underline bigtable objects like "Table", "Instance" ,"Cell" can be moved into a folder "model" as it represents direct data present in google could bigtable and keep its Admin classes on the normal hierarchy as follows
"google/cloud/bigtable/model/table.h"  ====> google::cloud::bigtable::model::Table
"google/cloud/bigtable/TableAdmin.h" ====>  google::cloud::bigtable::TableAdmin
Similar for operations like read, readwrite and policy etc.
So it will group the related classes and single folder will not have lots of classes together.

**Comment by mbrukman** [comment]
`google/cloud/bigtable/table.h` and `::google::cloud::bigtable::Table` LGTM, because it will match what is done for other languages that similarly have namespaces, e.g., see:

* Python: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/bigtable/google/cloud/bigtable
* Java: https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable
* .NET: https://github.com/GoogleCloudPlatform/google-cloud-dotnet/tree/master/apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2
